<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified"
           elementFormDefault="qualified">
    <xs:element name="expenses">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="expense" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="description"/>
                            <xs:element type="xs:string" name="currency_type"/>
                            <xs:element type="xs:string" name="amount"/>
                            <xs:element type="xs:string" name="date"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>